---
title: "Paper Figures Replication"
output: html_document
date: "2023-06-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load libraries.
```{r}
library(ggplot2)
library(gridExtra)
```

Load data.
```{r}
load("paper_replication_data.rdata")

# Remove 116th Congress from House lists - the data is incomplete
figure_A_results <- figure_A_results[figure_A_results$session != 116, ] 
figure_C_results <- figure_C_results[figure_C_results$session != 116, ] 
figure_E_results <- figure_E_results[figure_E_results$session != 116, ] 
```

```{r}
figure_B_results$session <- as.numeric(figure_B_results$session)
figure_A_results$session <- as.numeric(figure_A_results$session)
figure_C_results$session <- as.numeric(figure_C_results$session)
figure_D_results$session <- as.numeric(figure_D_results$session)
figure_E_results$session <- as.numeric(figure_E_results$session)
figure_F_results$session <- as.numeric(figure_F_results$session)

republican_sessions_H <- data.frame(
  session_start = c(108, 112, 118),
  session_end = c(109, 115, 118)
)

republican_sessions_S <- data.frame(
  session_start = c(108, 114),
  session_end = c(109, 116)
)

```

## Figures A & B
```{r}

# Figure A
plot_A <- ggplot(data = figure_A_results, aes(x = session, y = prop_pos_all_H)) +
  geom_line(color = "black", linetype = "solid") +
  geom_line(aes(y = prop_neg_all_H), color = "black", linetype = "dashed") +
  labs(x = "Session", y = "Proportion of all dyads", title = "House of Representatives") +
  labs(x = "Session", y = "Proportion of all dyads", title = "House of Representatives") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "top") +
  coord_cartesian(ylim = c(0, 1)) + # Set y-axis range
    geom_rect(
    data = republican_sessions_H,
    aes(xmin = session_start - 0.5, xmax = session_end + 0.5,ymin = -Inf,ymax = Inf),
    fill = "darkred",
    alpha = 0.2,
    inherit.aes = FALSE) + 
  scale_x_continuous(labels = function(x) as.integer(x))


# Figure B
plot_B <- ggplot(data = figure_B_results, aes(x = session, y = prop_pos_all_S)) +
  geom_line(color = "black", linetype = "solid") +
  geom_line(aes(y = prop_neg_all_S), color = "black", linetype = "dashed") +
  labs(x = "Session", y = "Proportion of all dyads", title = "Senate") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "top") +
  coord_cartesian(ylim = c(0, 1)) + # Set y-axis range
    geom_rect(
    data = republican_sessions_S,
    aes(xmin = session_start - 0.5, xmax = session_end + 0.5,ymin = -Inf,ymax = Inf),
    fill = "darkred",
    alpha = 0.2,
    inherit.aes = FALSE) + 
  scale_x_continuous(labels = function(x) as.integer(x))

```

```{r}

# Arrange plots side by side
plots_A_B <- grid.arrange(plot_A, plot_B, ncol = 2)
plots_A_B
```


## Figures C & D
```{r}

# Figure C
plot_C <- ggplot(data = figure_C_results, aes(x = session, y = prop_pos_within_H)) +
  geom_line(color = "black", linetype = "solid") +
  geom_line(aes(y = prop_neg_between_H), color = "black", linetype = "dashed") +
  labs(x = "Session", y = "Proportion of specified sign dyads", title = "House of Representatives") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "top") +
  coord_cartesian(ylim = c(0.8, 1)) + # Set y-axis range
    geom_rect(
    data = republican_sessions_H,
    aes(xmin = session_start - 0.5, xmax = session_end + 0.5,ymin = -Inf,ymax = Inf),
    fill = "darkred",
    alpha = 0.2,
    inherit.aes = FALSE)  + 
  scale_x_continuous(labels = function(x) as.integer(x))

# Figure D
plot_D <- ggplot(data = figure_D_results, aes(x = session, y = prop_pos_within_S)) +
  geom_line(color = "black", linetype = "solid") +
  geom_line(aes(y = prop_neg_between_S), color = "black", linetype = "dashed") +
  labs(x = "Session", y = "Proportion of specified sign dyads", title = "Senate") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "top") +
  coord_cartesian(ylim = c(0.8, 1))  + # Set y-axis range
    geom_rect(
    data = republican_sessions_S,
    aes(xmin = session_start - 0.5, xmax = session_end + 0.5,ymin = -Inf,ymax = Inf),
    fill = "darkred",
    alpha = 0.2,
    inherit.aes = FALSE) + 
  scale_x_continuous(labels = function(x) as.integer(x))
```

```{r}
# Arrange plots side by side
plots_C_D <- grid.arrange(plot_C, plot_D, ncol = 2)
plots_C_D
```

## Figures E & F
```{r}

# Figure E
plot_E <- ggplot(data = figure_E_results, aes(x = session, y = prop_neg_within_dem_H)) +
  geom_line(color = "blue", linetype = "solid") +
  geom_line(aes(y = prop_neg_within_rep_H), color = "red", linetype = "solid") +
  labs(x = "Session", y = "Proportion of negative ties w/in party", title = "House of Representatives") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  coord_cartesian(ylim = c(0, 0.1))  +    # Set y-axis range
    geom_rect(
    data = republican_sessions_H,
    aes(xmin = session_start - 0.5, xmax = session_end + 0.5,ymin = -Inf,ymax = Inf),
    fill = "darkred",
    alpha = 0.2,
    inherit.aes = FALSE) +
  scale_x_continuous(labels = function(x) as.integer(x))


# Figure F
plot_F <- ggplot(data = figure_F_results, aes(x = session, y = prop_neg_within_dem_S)) +
  geom_line(color = "blue", linetype = "solid") +
  geom_line(aes(y = prop_neg_within_rep_S), color = "red", linetype = "solid") +
  labs(x = "Session", y = "Proportion of negative ties w/in party", title = "Senate") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  coord_cartesian(ylim = c(0, 0.1))  + # Set y-axis range
    geom_rect(
    data = republican_sessions_S,
    aes(xmin = session_start - 0.5, xmax = session_end + 0.5,ymin = -Inf,ymax = Inf),
    fill = "darkred",
    alpha = 0.2,
    inherit.aes = FALSE) + 
  scale_x_continuous(labels = function(x) as.integer(x)) 
```


```{r}
# Arrange plots side by side
plots_E_F <- grid.arrange(plot_E, plot_F, ncol = 2)
plots_E_F
```

Save plots.
```{r}
ggsave(filename = "figures/A_&_B.jpg", plot = plots_A_B, device = "jpeg", width = 7, height = 3.5)
ggsave(filename = "figures/C_&_D.jpg", plot = plots_C_D, device = "jpeg", width = 7, height = 3.5)
ggsave(filename = "figures/E_&_F.jpg", plot = plots_E_F, device = "jpeg", width = 7, height = 3.5)

```

